use airsupply;


INSERT INTO `product`(`PRODUCT_ID`, `PRODUCT_NAME`, `PRODUCT_DESCRIPTION`, `PRODUCT_PRICE`) VALUES
(1122,'Airframe fasteners','Airframe fasteners by Hulkey Fasteners',4.25),
(1243,'Airframe fasteners','Airframe fasteners by Alum Sheeting',4.25),
(5462,'Shielded Cable/ft.','Shielded Cable/ft. by Fast-Tie Aerospace',1.05),
(5319,'Shielded Cable/ft.','Shielded Cable/ft. by Steelpin Inc.',1.1),
(3166,'Electrical Connector','Electrical Connector by Hulkey Fasteners',1.25),
(4312,'Bolt-nut package','Bolt-nut package by Steelpin Inc.',3.75),
(6321,'O-Ring','O-Ring by Fast-Tie Aerospace',2.45),
(7260,'Pressure Gauge','Pressure Gauge by Durrable Products',90),
(9966,'Hatch Decal','Hatch Decal by Hulkey Fasteners',0.75),
(5234,'Electrical Connector','Electrical Connector by Steelpin Inc.',1.65),
(5417,'Control Panel','Control Panel by Alum Sheeting',255),
(4111,'Bolt-nut package','Bolt-nut package by Spacetime Technologies',3.55),
(5066,'Shielded Cable/ft.','Shielded Cable/ft. by Hulkey Fasteners',0.95),
(7258,'Pressure Gauge','Pressure Gauge by Manley Valve',100.5),
(9752,'Gasket','Gasket by Spacetime Technologies',4.05),
(9764,'Gasket','Gasket by Pylon Accessories',3.75),
(1369,'Airframe fasteners','Airframe fasteners by Durrable Products',4.2),
(6431,'O-Ring','O-Ring by Manley Valve',2.85),
(5125,'Shielded Cable/ft.','Shielded Cable/ft. by Spacetime Technologies',1.15),
(5166,'Electrical Connector','Electrical Connector by Fast-Tie Aerospace',1.25),
(6433,'O-Ring','O-Ring by Pylon Accessories',2.95),
(9399,'Gasket','Gasket by Durrable Products',3.65),
(4569,'Bolt-nut package','Bolt-nut package by Durrable Products',3.5),
(6489,'O-Ring','O-Ring by Spacetime Technologies',3),
(8148,'Machined Valve','Machined Valve by Manley Valve',655.5),
(4224,'Bolt-nut package','Bolt-nut package by Alum Sheeting',3.95),
(5454,'Control Panel','Control Panel by Durrable Products',220),
(5275,'Shielded Cable/ft.','Shielded Cable/ft. by Durrable Products',1),
(5634,'Side Panel','Side Panel by Alum Sheeting',185),
(5689,'Side Panel','Side Panel by Fast-Tie Aerospace',175),
(8008,'Machined Valve','Machined Valve by Steelpin Inc.',645),
(7268,'Pressure Gauge','Pressure Gauge by Fast-Tie Aerospace',95),
(9955,'Door Decal','Door Decal by Manley Valve',0.55),
(9977,'Panel Decal','Panel Decal by Manley Valve',1),
(5677,'Side Panel','Side Panel by Steelpin Inc.',195),
(9967,'Hatch Decal','Hatch Decal by Manley Valve',0.85);